services:
  web:
    build: .
    container_name: event_management_web
    ports:
      - "8080:80"  
    volumes:
      - .:/var/www/html 
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: mysql:5.7  
    container_name: event_management_dbs
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: event_management
      MYSQL_USER: Lacelyn
      MYSQL_PASSWORD: maximkerno 
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin  
    container_name: event_management_phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"  
    networks:
      - app_network
networks:
  app_network:
volumes:
  db_data:
